//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assignment5_6.EncryptionServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://assignment5_6.org/", ConfigurationName="EncryptionServiceReference.EncryptionServiceSoap")]
    public interface EncryptionServiceSoap {
        
        // CODEGEN: Generating message contract since element name input from namespace http://assignment5_6.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://assignment5_6.org/HashString", ReplyAction="*")]
        Assignment5_6.EncryptionServiceReference.HashStringResponse HashString(Assignment5_6.EncryptionServiceReference.HashStringRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://assignment5_6.org/HashString", ReplyAction="*")]
        System.Threading.Tasks.Task<Assignment5_6.EncryptionServiceReference.HashStringResponse> HashStringAsync(Assignment5_6.EncryptionServiceReference.HashStringRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HashStringRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HashString", Namespace="http://assignment5_6.org/", Order=0)]
        public Assignment5_6.EncryptionServiceReference.HashStringRequestBody Body;
        
        public HashStringRequest() {
        }
        
        public HashStringRequest(Assignment5_6.EncryptionServiceReference.HashStringRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://assignment5_6.org/")]
    public partial class HashStringRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string input;
        
        public HashStringRequestBody() {
        }
        
        public HashStringRequestBody(string input) {
            this.input = input;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HashStringResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HashStringResponse", Namespace="http://assignment5_6.org/", Order=0)]
        public Assignment5_6.EncryptionServiceReference.HashStringResponseBody Body;
        
        public HashStringResponse() {
        }
        
        public HashStringResponse(Assignment5_6.EncryptionServiceReference.HashStringResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://assignment5_6.org/")]
    public partial class HashStringResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HashStringResult;
        
        public HashStringResponseBody() {
        }
        
        public HashStringResponseBody(string HashStringResult) {
            this.HashStringResult = HashStringResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface EncryptionServiceSoapChannel : Assignment5_6.EncryptionServiceReference.EncryptionServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EncryptionServiceSoapClient : System.ServiceModel.ClientBase<Assignment5_6.EncryptionServiceReference.EncryptionServiceSoap>, Assignment5_6.EncryptionServiceReference.EncryptionServiceSoap {
        
        public EncryptionServiceSoapClient() {
        }
        
        public EncryptionServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EncryptionServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EncryptionServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EncryptionServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Assignment5_6.EncryptionServiceReference.HashStringResponse Assignment5_6.EncryptionServiceReference.EncryptionServiceSoap.HashString(Assignment5_6.EncryptionServiceReference.HashStringRequest request) {
            return base.Channel.HashString(request);
        }
        
        public string HashString(string input) {
            Assignment5_6.EncryptionServiceReference.HashStringRequest inValue = new Assignment5_6.EncryptionServiceReference.HashStringRequest();
            inValue.Body = new Assignment5_6.EncryptionServiceReference.HashStringRequestBody();
            inValue.Body.input = input;
            Assignment5_6.EncryptionServiceReference.HashStringResponse retVal = ((Assignment5_6.EncryptionServiceReference.EncryptionServiceSoap)(this)).HashString(inValue);
            return retVal.Body.HashStringResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Assignment5_6.EncryptionServiceReference.HashStringResponse> Assignment5_6.EncryptionServiceReference.EncryptionServiceSoap.HashStringAsync(Assignment5_6.EncryptionServiceReference.HashStringRequest request) {
            return base.Channel.HashStringAsync(request);
        }
        
        public System.Threading.Tasks.Task<Assignment5_6.EncryptionServiceReference.HashStringResponse> HashStringAsync(string input) {
            Assignment5_6.EncryptionServiceReference.HashStringRequest inValue = new Assignment5_6.EncryptionServiceReference.HashStringRequest();
            inValue.Body = new Assignment5_6.EncryptionServiceReference.HashStringRequestBody();
            inValue.Body.input = input;
            return ((Assignment5_6.EncryptionServiceReference.EncryptionServiceSoap)(this)).HashStringAsync(inValue);
        }
    }
}
